"""The physics configs for the anatomy body, built from the owner's DEPLOYED ones (decision A-7).

Inputs (read only): Data/F4SE/Plugins/ocbp.ini (from MadKita's Actual Jiggle) and
OCBPCollisionConfig.txt (from Jiggle Physics); the plugin is OCBPC 0.3. Nothing they tune is
dropped; the output (build/config/, never committed: it carries their work, A-2) differs by:

  ocbp.ini
    - [Attach]/[Attach.A] lines naming a bone the ZeX skeleton does not have are commented out,
      with the reason. Measured: 12 of 17 (3BBB bone names); they could never move anything.
    - Our bones: the vagina _CBP_ twins (A-6: animations keep the animated bones) and the anus
      bones (ZeX has no anus twins), each with a spring section of its own: stiff and damped,
      so walking does not wobble them, but linear near 1 so a collision's push is not scaled away.
  OCBPCollisionConfig.txt
    - Affected: the lower labia twins (Vagina_CBP_L_02 / _R_02) and the four anus bones.
      Colliders: the penis bones from Penis_01 out, plus the hands and fingers already listed.
    - Every sphere of ours sits ON its bone (offset 0,0,0). Whether this OCBPC build rotates an
      offset by the bone is unproven (the deployed breast spheres read correctly only as WORLD
      offsets, but no body ever carried breast weights to test them), and a zero offset means
      the same thing either way. The opening then comes from where the bones are: L_02 sits
      0.64 left of the midline and R_02 0.53 right, so a penis on the midline pushes them apart;
      the anus bones ring the opening (back, front, left, right).
    - Penis_00 is left out: every skeleton has the penis bones, and a female's own Penis_00
      rests 2 units from her vulva, where it would hold her open.

    python tools/physics_config.py
"""
import pathlib
import re

import zex_bones as zb

ROOT = pathlib.Path(__file__).resolve().parent.parent
PLUGINS = zb.ab.DEFAULT_DATA / 'F4SE/Plugins'
OUT = ROOT / 'build/config'

ATTACH = [('Vagina_CBP_00', 'Clitoris'),
          ('Vagina_CBP_L_01', 'Labia'), ('Vagina_CBP_R_01', 'Labia'),
          ('Vagina_CBP_L_02', 'Labia'), ('Vagina_CBP_R_02', 'Labia'),
          ('Anus_01', 'Anus'), ('Anus_02', 'Anus'), ('Anus_03', 'Anus'), ('Anus_04', 'Anus')]

SPRING = dict(stiffness=60.0, stiffness2=60.0, damping=6.0, timetick=4.0, timeStep=0.020,
              gravityBias=0.0, gravityCorrection=0.0, cogOffsetX=0.0, cogOffsetY=0.0, cogOffsetZ=0.0,
              rotationalX=0.0, rotationalY=0.0, rotationalZ=0.0, rotateLinearX=0.0, rotateLinearY=0.0,
              rotateLinearZ=0.0, rotateRotationX=0.0, rotateRotationY=0.0, rotateRotationZ=0.0, absRotX=0)
SECTIONS = {
    'Labia': dict(SPRING, linearX=0.9, linearY=0.9, linearZ=0.9, maxoffsetX=2.5, maxoffsetY=2.5, maxoffsetZ=2.5),
    'Clitoris': dict(SPRING, linearX=0.4, linearY=0.4, linearZ=0.4, maxoffsetX=0.8, maxoffsetY=0.8, maxoffsetZ=0.8),
    'Anus': dict(SPRING, linearX=0.9, linearY=0.9, linearZ=0.9, maxoffsetX=1.5, maxoffsetY=1.5, maxoffsetZ=1.5),
}
AFFECTED = {'Vagina_CBP_L_02': 0.6, 'Vagina_CBP_R_02': 0.6,
            'Anus_01': 0.4, 'Anus_02': 0.4, 'Anus_03': 0.4, 'Anus_04': 0.4}
COLLIDERS = {'Penis_01': 1.3, 'Penis_02': 1.3, 'Penis_03': 1.3, 'Penis_04': 1.25, 'Penis_05': 1.1}


def sections(text):
    """[(header or None, [lines])] in file order."""
    out, cur = [], (None, [])
    for line in text.splitlines():
        m = re.match(r'^\s*\[([^\]]+)\]', line)
        if m:
            out.append(cur)
            cur = (m.group(1), [line])
        else:
            cur[1].append(line)
    out.append(cur)
    return out


def ocbp(text, skeleton):
    parts = sections(text)
    dead = []
    new = []
    for name, lines in parts:
        if name in ('Attach', 'Attach.A'):
            kept = []
            for line in lines:
                m = re.match(r'^\s*([A-Za-z0-9_]+)\s*=', line)
                if m and not line.lstrip().startswith(';') and m.group(1) not in skeleton:
                    kept.append(f'; not in the ZeX skeleton, so nothing to move: {line.strip()}')
                    dead.append(m.group(1))
                else:
                    kept.append(line)
            if name == 'Attach':
                kept += ['; --- anatomy (fo4-anatomy A-7): vagina physics on the _CBP_ twins, anus on its bones'] + \
                        [f'{b}={s}' for b, s in ATTACH]
            new.append((name, kept))
        else:
            new.append((name, lines))
    body = []
    for name, lines in new:
        body += lines
    for sec, vals in SECTIONS.items():
        body += ['', f'[{sec}]'] + [f'{k}={v}' for k, v in vals.items()]
    header = ['; Generated by fo4-anatomy tools/physics_config.py from the deployed ocbp.ini.',
              f'; {len(dead)} attach line(s) commented out (bones missing from ZeX); anatomy bones appended.']
    return '\n'.join(header + body) + '\n', dead


def collisions(text):
    parts = sections(text)
    out = []
    for name, lines in parts:
        if name == 'AffectedNodes':
            lines = _append_list(lines, AFFECTED)
        elif name == 'ColliderNodes':
            lines = _append_list(lines, COLLIDERS)
        out += lines
    out += ['', '#' * 78, '# Anatomy spheres (fo4-anatomy A-7): on the bone, offset 0,0,0 -- see physics_config.py',
            '#' * 78]
    for node, r in list(AFFECTED.items()) + list(COLLIDERS.items()):
        out += ['', f'[{node}]', f'0,0,0,{r}']
    return '\n'.join(out) + '\n'


def _append_list(lines, names):
    """Node names go right after the last listed name, before the section's trailing blank lines."""
    last = max((i for i, l in enumerate(lines) if l.strip() and not l.strip().startswith('#')
                and not l.strip().startswith('[')), default=0)
    return lines[:last + 1] + list(names) + lines[last + 1:]


def main():
    skeleton = set(zb.skeleton_world(zb.SKELETON))
    OUT.mkdir(parents=True, exist_ok=True)
    src_ini = (PLUGINS / 'ocbp.ini').read_text(encoding='utf-8', errors='replace')
    ini, dead = ocbp(src_ini, skeleton)
    (OUT / 'ocbp.ini').write_text(ini, encoding='utf-8')
    src_col = (PLUGINS / 'OCBPCollisionConfig.txt').read_text(encoding='utf-8', errors='replace')
    (OUT / 'OCBPCollisionConfig.txt').write_text(collisions(src_col), encoding='utf-8')
    missing = [b for b, _ in ATTACH if b not in skeleton] + [n for n in list(AFFECTED) + list(COLLIDERS) if n not in skeleton]
    print(f'ocbp.ini: {len(dead)} dead attach lines commented out ({sorted(set(dead))}); '
          f'{len(ATTACH)} anatomy bones attached in {len(SECTIONS)} new sections')
    print(f'OCBPCollisionConfig.txt: +{len(AFFECTED)} affected, +{len(COLLIDERS)} colliders, all spheres on their bones')
    print(f'anatomy bones missing from the skeleton: {missing or "none"}')
    if missing:
        raise SystemExit(1)


if __name__ == '__main__':
    main()
